/**
 * Every Focus URL in one place. Screens and fixtures link only through these builders, so there are no placeholder
 * links ("#") and a renamed route breaks the type-check instead of a click.
 */
export const R = {
  today: "/focus",
  todayManager: "/focus/today-manager",
  approvals: "/focus/approvals",
  approval: (id: string) => `/focus/approvals/${id}`,
  projects: "/focus/projects",
  newProject: "/focus/projects/new",
  project: (id: string) => `/focus/projects/${id}`,
  projectExecution: (id: string) => `/focus/projects/${id}/execution`,
  client: (id: string) => `/focus/clients/${id}`,
  clientBrain: (id: string) => `/focus/clients/${id}/brain`,
  marketingPlan: "/focus/marketing/plan",
  marketingBoard: "/focus/marketing/board",
  inspiration: "/focus/marketing/inspiration",
  trends: "/focus/marketing/trends",
  briefs: "/focus/marketing/briefs",
  prompts: "/focus/marketing/prompts",
  campaign: (id: string) => `/focus/marketing/campaigns/${id}`,
  studio: "/focus/studio",
  studioNew: "/focus/studio/new",
  studioDirections: "/focus/studio/new/directions",
  design: (id: string) => `/focus/studio/${id}`,
  designEdit: (id: string) => `/focus/studio/${id}/edit`,
  designPublish: (id: string) => `/focus/studio/${id}/publish`,
  sales: "/focus/sales",
  lead: (id: string) => `/focus/sales/leads/${id}`,
  proposals: "/focus/sales/proposals",
  proposal: (id: string) => `/focus/sales/proposals/${id}`,
  outreach: "/focus/sales/outreach",
  discovery: "/focus/sales/discovery",
  work: "/focus/work",
  workList: "/focus/work/list",
  workBoard: "/focus/work/board",
  workTask: "/focus/work/task",
  workTime: "/focus/work/time",
  workStates: "/focus/work/states",
  allTasks: "/focus/work/all-tasks",
  task: (id: string, view: "list" | "board" = "list") => `/focus/work/${view}?task=${encodeURIComponent(id)}`,
  comms: "/focus/comms",
  calendar: "/focus/comms/calendar",
  reports: "/focus/reports",
  reportHours: "/focus/reports/hours",
  reportWeekly: "/focus/reports/weekly",
  activity: "/focus/reports/activity",
  settings: "/focus/settings/connections",
  settingsUsers: "/focus/settings/users",
  settingsBusiness: "/focus/settings/business",
  notifications: "/focus/notifications",
  screens: "/focus/screens",
  mobile: (n: number) => `/focus/m/${n}`,
} as const;
