/** Generated by the Focus converter: every handoff screen, its URL, page mode and top-bar state. */
export type ScreenMode = "app" | "focus" | "mobile";
export type NavKey = "today" | "plan" | "projects" | "marketing" | "sales" | "work" | "comms" | "reports" | "settings";
export type ScreenEntry = { id: string; title: string; subtitle: string; route: string; mode: ScreenMode;
  nav: { active: NavKey; client: string; bell: boolean; avatar: string } | null; notes: string[] };

/**
 * Mobile frames (M1–M10) are not separate screens: each is the real responsive screen at 390px. `/focus/m/<n>`
 * redirects there; the screen map previews it inside a phone frame. M7 shows two screens side by side.
 */
export const MOBILE_TARGETS: Record<string, string[]> = {
  M1: ["/focus"], M2: ["/focus/approvals"], M3: ["/focus/approvals/promo-1plus1"], M4: ["/focus/approvals/proposal-noa"],
  M5: ["/focus/projects/umino"], M6: ["/focus/work/all-tasks"], M7: ["/focus/sales", "/focus/sales/leads/noa-cohen"],
  M8: ["/focus/approvals/content-sushi-story"], M9: ["/focus/work"], M10: ["/focus/work/list?task=t-post45"],
};

export const SCREENS: ScreenEntry[] = [
 {
  "id": "D1",
  "title": "היום שלי · לפי זמן",
  "subtitle": "",
  "route": "/focus",
  "mode": "app",
  "nav": {
   "active": "today",
   "client": "כל הלקוחות",
   "bell": true,
   "avatar": "ר"
  },
  "notes": []
 },
 {
  "id": "D2",
  "title": "סביבת פרויקט › סקירה",
  "subtitle": "",
  "route": "/focus/projects/umino",
  "mode": "app",
  "nav": {
   "active": "projects",
   "client": "UMINO",
   "bell": false,
   "avatar": "ד"
  },
  "notes": []
 },
 {
  "id": "D3",
  "title": "סביבת פרויקט › ביצוע › משימות",
  "subtitle": "זרימה 2 · משימה חסומה",
  "route": "/focus/projects/umino/execution",
  "mode": "app",
  "nav": {
   "active": "projects",
   "client": "UMINO",
   "bell": false,
   "avatar": "ד"
  },
  "notes": []
 },
 {
  "id": "D4",
  "title": "מרכז האישורים · רשימה",
  "subtitle": "",
  "route": "/focus/approvals",
  "mode": "app",
  "nav": {
   "active": "today",
   "client": "כל הלקוחות",
   "bell": false,
   "avatar": "ר"
  },
  "notes": []
 },
 {
  "id": "D5",
  "title": "אישור · פירוט · מצב פוקוס",
  "subtitle": "זרימה 3 · סיכון בינוני",
  "route": "/focus/approvals/promo-1plus1",
  "mode": "focus",
  "nav": {
   "active": "today",
   "client": "כל הלקוחות",
   "bell": false,
   "avatar": "ר"
  },
  "notes": []
 },
 {
  "id": "D6",
  "title": "אישורים · מצב פוקוס · סיכום לפני ביצוע",
  "subtitle": "פעולה בסיכון גבוה, שלב 2 מתוך 2",
  "route": "/focus/approvals/proposal-noa",
  "mode": "focus",
  "nav": {
   "active": "today",
   "client": "כל הלקוחות",
   "bell": false,
   "avatar": "ר"
  },
  "notes": []
 },
 {
  "id": "D7",
  "title": "אישור תוכן · בקשת תיקון",
  "subtitle": "זרימה 5",
  "route": "/focus/approvals/content-sushi-story",
  "mode": "focus",
  "nav": {
   "active": "today",
   "client": "כל הלקוחות",
   "bell": false,
   "avatar": "ר"
  },
  "notes": []
 },
 {
  "id": "D8",
  "title": "היום שלי · מנהלת · נתונים חלקיים ותקלה",
  "subtitle": "מצבי קצה והרשאות",
  "route": "/focus/today-manager",
  "mode": "app",
  "nav": {
   "active": "today",
   "client": "כל הלקוחות",
   "bell": false,
   "avatar": "ד"
  },
  "notes": []
 },
 {
  "id": "E1",
  "title": "קמפיין",
  "subtitle": "נקודת הכניסה ליצירת תוכן",
  "route": "/focus/marketing/campaigns/thursday-sushi",
  "mode": "app",
  "nav": {
   "active": "marketing",
   "client": "UMINO",
   "bell": false,
   "avatar": "ד"
  },
  "notes": []
 },
 {
  "id": "E2",
  "title": "סטודיו התוכן · מסך פתיחה",
  "subtitle": "",
  "route": "/focus/studio",
  "mode": "app",
  "nav": {
   "active": "marketing",
   "client": "כל הלקוחות",
   "bell": false,
   "avatar": "ד"
  },
  "notes": []
 },
 {
  "id": "E3",
  "title": "יצירה · שלבים 1–3: מטרה, פורמט ובריף",
  "subtitle": "",
  "route": "/focus/studio/new",
  "mode": "focus",
  "nav": {
   "active": "marketing",
   "client": "כל הלקוחות",
   "bell": false,
   "avatar": "ר"
  },
  "notes": []
 },
 {
  "id": "E4",
  "title": "יצירה · שלב 4: כיוונים",
  "subtitle": "כולל מצב \"מעבד\"",
  "route": "/focus/studio/new/directions",
  "mode": "focus",
  "nav": {
   "active": "marketing",
   "client": "כל הלקוחות",
   "bell": false,
   "avatar": "ר"
  },
  "notes": []
 },
 {
  "id": "E5",
  "title": "סטודיו התוכן · כל הפורמטים יחד",
  "subtitle": "",
  "route": "/focus/studio/thursday-sushi",
  "mode": "focus",
  "nav": {
   "active": "marketing",
   "client": "כל הלקוחות",
   "bell": false,
   "avatar": "ר"
  },
  "notes": []
 },
 {
  "id": "E6",
  "title": "עורך · פורמט יחיד · אזורי בטיחות",
  "subtitle": "",
  "route": "/focus/studio/thursday-sushi/edit",
  "mode": "focus",
  "nav": {
   "active": "marketing",
   "client": "כל הלקוחות",
   "bell": false,
   "avatar": "ר"
  },
  "notes": []
 },
 {
  "id": "E7",
  "title": "יצוא ופרסום · אחרי אישור",
  "subtitle": "\"נשמר\", \"יוצא\", \"תוזמן\" ו\"פורסם\" הם מצבים נפרדים",
  "route": "/focus/studio/thursday-sushi/publish",
  "mode": "focus",
  "nav": {
   "active": "marketing",
   "client": "כל הלקוחות",
   "bell": false,
   "avatar": "ר"
  },
  "notes": []
 },
 {
  "id": "F1",
  "title": "לידים · רשימה",
  "subtitle": "",
  "route": "/focus/sales",
  "mode": "app",
  "nav": {
   "active": "sales",
   "client": "כל הלקוחות",
   "bell": false,
   "avatar": "ד"
  },
  "notes": []
 },
 {
  "id": "F2",
  "title": "מסך ליד",
  "subtitle": "זרימה 6 · נקודת התחלה",
  "route": "/focus/sales/leads/noa-cohen",
  "mode": "app",
  "nav": {
   "active": "sales",
   "client": "כל הלקוחות",
   "bell": false,
   "avatar": "ד"
  },
  "notes": []
 },
 {
  "id": "F3",
  "title": "הצעת מחיר · עריכה ותצוגה מקדימה",
  "subtitle": "",
  "route": "/focus/sales/proposals/corporate-hosting",
  "mode": "focus",
  "nav": {
   "active": "sales",
   "client": "כל הלקוחות",
   "bell": false,
   "avatar": "ר"
  },
  "notes": []
 },
 {
  "id": "F4",
  "title": "פניות יזומות · טיוטה ובדיקת עובדות",
  "subtitle": "",
  "route": "/focus/sales/outreach",
  "mode": "app",
  "nav": {
   "active": "sales",
   "client": "כל הלקוחות",
   "bell": false,
   "avatar": "ד"
  },
  "notes": []
 },
 {
  "id": "F5",
  "title": "משימות · כל הפרויקטים",
  "subtitle": "",
  "route": "/focus/work/all-tasks",
  "mode": "app",
  "nav": {
   "active": "work",
   "client": "כל הלקוחות",
   "bell": false,
   "avatar": "ד"
  },
  "notes": []
 },
 {
  "id": "F6",
  "title": "דואר · שיחה וטיוטת תשובה",
  "subtitle": "",
  "route": "/focus/comms",
  "mode": "app",
  "nav": {
   "active": "comms",
   "client": "כל הלקוחות",
   "bell": false,
   "avatar": "ד"
  },
  "notes": []
 },
 {
  "id": "G1",
  "title": "דוחות › יעדים וביצועים · מגירת מקור הנתון",
  "subtitle": "זרימה 8",
  "route": "/focus/reports",
  "mode": "app",
  "nav": {
   "active": "reports",
   "client": "UMINO",
   "bell": false,
   "avatar": "ר"
  },
  "notes": []
 },
 {
  "id": "G2",
  "title": "שעות ורווחיות",
  "subtitle": "",
  "route": "/focus/reports/hours",
  "mode": "app",
  "nav": {
   "active": "reports",
   "client": "כל הלקוחות",
   "bell": false,
   "avatar": "ר"
  },
  "notes": []
 },
 {
  "id": "G3",
  "title": "סקירה שבועית",
  "subtitle": "מה מבוסס נתונים ומה נוסח ב־AI",
  "route": "/focus/reports/weekly",
  "mode": "focus",
  "nav": {
   "active": "reports",
   "client": "כל הלקוחות",
   "bell": false,
   "avatar": "ר"
  },
  "notes": []
 },
 {
  "id": "G4",
  "title": "יומן פעולות",
  "subtitle": "",
  "route": "/focus/reports/activity",
  "mode": "app",
  "nav": {
   "active": "reports",
   "client": "כל הלקוחות",
   "bell": false,
   "avatar": "ר"
  },
  "notes": []
 },
 {
  "id": "G5",
  "title": "מוח העסק · UMINO",
  "subtitle": "מצב התוכן ומצב האימות בנפרד",
  "route": "/focus/clients/umino/brain",
  "mode": "app",
  "nav": {
   "active": "projects",
   "client": "UMINO",
   "bell": false,
   "avatar": "ד"
  },
  "notes": []
 },
 {
  "id": "G6",
  "title": "הגדרות › חיבורים · תקלה ב־Instagram",
  "subtitle": "זרימה 7",
  "route": "/focus/settings/connections",
  "mode": "app",
  "nav": {
   "active": "settings",
   "client": "Mytiv",
   "bell": false,
   "avatar": "ר"
  },
  "notes": []
 },
 {
  "id": "H1",
  "title": "כל הפרויקטים",
  "subtitle": "",
  "route": "/focus/projects",
  "mode": "app",
  "nav": {
   "active": "projects",
   "client": "כל הלקוחות",
   "bell": false,
   "avatar": "ר"
  },
  "notes": []
 },
 {
  "id": "H2",
  "title": "לקוח · UMINO",
  "subtitle": "",
  "route": "/focus/clients/umino",
  "mode": "app",
  "nav": {
   "active": "projects",
   "client": "כל הלקוחות",
   "bell": false,
   "avatar": "ר"
  },
  "notes": []
 },
 {
  "id": "H3",
  "title": "פרויקט חדש · שלב 3 מתוך 6",
  "subtitle": "",
  "route": "/focus/projects/new",
  "mode": "focus",
  "nav": {
   "active": "projects",
   "client": "כל הלקוחות",
   "bell": false,
   "avatar": "ר"
  },
  "notes": []
 },
 {
  "id": "H4",
  "title": "תוכנית שיווק",
  "subtitle": "",
  "route": "/focus/marketing/plan",
  "mode": "app",
  "nav": {
   "active": "marketing",
   "client": "כל הלקוחות",
   "bell": false,
   "avatar": "ר"
  },
  "notes": []
 },
 {
  "id": "H5",
  "title": "לוח עבודה · Kanban",
  "subtitle": "",
  "route": "/focus/marketing/board",
  "mode": "app",
  "nav": {
   "active": "marketing",
   "client": "כל הלקוחות",
   "bell": false,
   "avatar": "ר"
  },
  "notes": []
 },
 {
  "id": "H6",
  "title": "השראה ומודבורדים",
  "subtitle": "",
  "route": "/focus/marketing/inspiration",
  "mode": "app",
  "nav": {
   "active": "marketing",
   "client": "כל הלקוחות",
   "bell": false,
   "avatar": "ר"
  },
  "notes": []
 },
 {
  "id": "H7",
  "title": "הזדמנויות ומגמות",
  "subtitle": "",
  "route": "/focus/marketing/trends",
  "mode": "app",
  "nav": {
   "active": "marketing",
   "client": "כל הלקוחות",
   "bell": false,
   "avatar": "ר"
  },
  "notes": []
 },
 {
  "id": "H8",
  "title": "גילוי לידים · חיפוש ברקע",
  "subtitle": "",
  "route": "/focus/sales/discovery",
  "mode": "app",
  "nav": {
   "active": "sales",
   "client": "כל הלקוחות",
   "bell": false,
   "avatar": "ר"
  },
  "notes": []
 },
 {
  "id": "H9",
  "title": "הצעות מחיר · רשימה",
  "subtitle": "",
  "route": "/focus/sales/proposals",
  "mode": "app",
  "nav": {
   "active": "sales",
   "client": "כל הלקוחות",
   "bell": false,
   "avatar": "ר"
  },
  "notes": []
 },
 {
  "id": "H10",
  "title": "יומן · שבוע",
  "subtitle": "",
  "route": "/focus/comms/calendar",
  "mode": "app",
  "nav": {
   "active": "comms",
   "client": "כל הלקוחות",
   "bell": false,
   "avatar": "ר"
  },
  "notes": []
 },
 {
  "id": "H11",
  "title": "בריפים · תוצאת ניתוח",
  "subtitle": "מה כתוב בבריף ומה AI הסיק",
  "route": "/focus/marketing/briefs",
  "mode": "app",
  "nav": {
   "active": "marketing",
   "client": "כל הלקוחות",
   "bell": false,
   "avatar": "ר"
  },
  "notes": []
 },
 {
  "id": "H12",
  "title": "פרומפטים · בונה וספרייה",
  "subtitle": "",
  "route": "/focus/marketing/prompts",
  "mode": "app",
  "nav": {
   "active": "marketing",
   "client": "כל הלקוחות",
   "bell": false,
   "avatar": "ר"
  },
  "notes": []
 },
 {
  "id": "H13",
  "title": "הגדרות › משתמשים והרשאות",
  "subtitle": "",
  "route": "/focus/settings/users",
  "mode": "app",
  "nav": {
   "active": "settings",
   "client": "כל הלקוחות",
   "bell": false,
   "avatar": "ר"
  },
  "notes": []
 },
 {
  "id": "H14",
  "title": "הגדרות › AI · העסק · Brand Kit",
  "subtitle": "",
  "route": "/focus/settings/business",
  "mode": "app",
  "nav": {
   "active": "settings",
   "client": "כל הלקוחות",
   "bell": false,
   "avatar": "ר"
  },
  "notes": []
 },
 {
  "id": "H15",
  "title": "התראות · ארבע קבוצות",
  "subtitle": "",
  "route": "/focus/notifications",
  "mode": "app",
  "nav": {
   "active": "today",
   "client": "כל הלקוחות",
   "bell": false,
   "avatar": "ר"
  },
  "notes": []
 },
 {
  "id": "W1",
  "title": "עבודה › המשימות שלי",
  "subtitle": "מסודר לפי זמן · טיימר פעיל קבוע למטה",
  "route": "/focus/work",
  "mode": "app",
  "nav": {
   "active": "work",
   "client": "כל הלקוחות",
   "bell": false,
   "avatar": "ר"
  },
  "notes": []
 },
 {
  "id": "W2",
  "title": "סביבת פרויקט › ביצוע › Mytiv Work · List",
  "subtitle": "תת־משימות מתקפלות · תלויות · checklist בשורה",
  "route": "/focus/work/list",
  "mode": "app",
  "nav": {
   "active": "work",
   "client": "כל הלקוחות",
   "bell": false,
   "avatar": "ר"
  },
  "notes": []
 },
 {
  "id": "W3",
  "title": "ביצוע › Kanban לפי סטטוס",
  "subtitle": "גרירה או מקלדת · Space לבחירה, חצים להזזה",
  "route": "/focus/work/board",
  "mode": "app",
  "nav": {
   "active": "work",
   "client": "כל הלקוחות",
   "bell": false,
   "avatar": "ר"
  },
  "notes": []
 },
 {
  "id": "W4",
  "title": "מגירת פרטי משימה",
  "subtitle": "חוזה הרכיב המלא · נפתחת מעל כל תצוגה",
  "route": "/focus/work/task",
  "mode": "app",
  "nav": {
   "active": "work",
   "client": "כל הלקוחות",
   "bell": false,
   "avatar": "ר"
  },
  "notes": []
 },
 {
  "id": "W5",
  "title": "פס טיימר קבוע · דוח שעות בסיסי",
  "subtitle": "",
  "route": "/focus/work/time",
  "mode": "app",
  "nav": {
   "active": "work",
   "client": "כל הלקוחות",
   "bell": false,
   "avatar": "ר"
  },
  "notes": []
 },
 {
  "id": "W6",
  "title": "מצבי מערכת · יצירה מהירה · מתוכנן",
  "subtitle": "",
  "route": "/focus/work/states",
  "mode": "app",
  "nav": {
   "active": "work",
   "client": "כל הלקוחות",
   "bell": false,
   "avatar": "ר"
  },
  "notes": []
 },
 {
  "id": "M1",
  "title": "היום שלי",
  "subtitle": "",
  "route": "/focus/m/1",
  "mode": "mobile",
  "nav": null,
  "notes": [
   "סדר התוכן: דורש פעולה, יומן, מה תקוע, פרויקטים בסיכון, מדדים. האחרונים נמצאים מתחת לקו הגלילה."
  ]
 },
 {
  "id": "M2",
  "title": "אישורים · תור",
  "subtitle": "",
  "route": "/focus/m/2",
  "mode": "mobile",
  "nav": null,
  "notes": []
 },
 {
  "id": "M3",
  "title": "פירוט אישור · מבצע 1+1",
  "subtitle": "",
  "route": "/focus/m/3",
  "mode": "mobile",
  "nav": null,
  "notes": []
 },
 {
  "id": "M4",
  "title": "סיכום לפני ביצוע · גיליון תחתון",
  "subtitle": "",
  "route": "/focus/m/4",
  "mode": "mobile",
  "nav": null,
  "notes": []
 },
 {
  "id": "M5",
  "title": "פרויקט · סקירה",
  "subtitle": "",
  "route": "/focus/m/5",
  "mode": "mobile",
  "nav": null,
  "notes": []
 },
 {
  "id": "M6",
  "title": "משימות",
  "subtitle": "",
  "route": "/focus/m/6",
  "mode": "mobile",
  "nav": null,
  "notes": []
 },
 {
  "id": "M7",
  "title": "לידים · ליד",
  "subtitle": "",
  "route": "/focus/m/7",
  "mode": "mobile",
  "nav": null,
  "notes": []
 },
 {
  "id": "M8",
  "title": "אישור תוכן",
  "subtitle": "",
  "route": "/focus/m/8",
  "mode": "mobile",
  "nav": null,
  "notes": []
 },
 {
  "id": "M9",
  "title": "עבודה · המשימות שלי",
  "subtitle": "",
  "route": "/focus/m/9",
  "mode": "mobile",
  "nav": null,
  "notes": [
   "אותם buckets של הדסקטופ. הטיימר הפעיל נשאר מעל הניווט בכל מעבר מסך."
  ]
 },
 {
  "id": "M10",
  "title": "מגירת משימה · גיליון תחתון",
  "subtitle": "",
  "route": "/focus/m/10",
  "mode": "mobile",
  "nav": null,
  "notes": [
   "מגירת הדסקטופ כגיליון תחתון: אותו חוזה — סטטוס, עדיפות, אחראי, תלות, טיימר, checklist, תגובות."
  ]
 }
];
